https://www.kaggle.com/c/bike-sharing-demand/data?select=train.csv

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('data1/bike-sharing-demand/train.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  object
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB

In [125]:
dropped_df = df.drop(['datetime','casual','registered'], axis=1)
dropped_df

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count
0,1,0,0,1,9.84,14.395,81,0.0000,16
1,1,0,0,1,9.02,13.635,80,0.0000,40
2,1,0,0,1,9.02,13.635,80,0.0000,32
3,1,0,0,1,9.84,14.395,75,0.0000,13
4,1,0,0,1,9.84,14.395,75,0.0000,1
...,...,...,...,...,...,...,...,...,...
10881,4,0,1,1,15.58,19.695,50,26.0027,336
10882,4,0,1,1,14.76,17.425,57,15.0013,241
10883,4,0,1,1,13.94,15.910,61,15.0013,168
10884,4,0,1,1,13.94,17.425,61,6.0032,129
10885,4,0,1,1,13.12,16.665,66,8.9981,88

In [126]:
X = dropped_df.drop('count',axis=1).values
y = dropped_df['count']

In [ ]:
from sklearn.preprocessing import StandardScaler

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [128]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [129]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(155.13350586282306), np.float64(24066.40464129056))

In [130]:
r2_score(y_test, y_pred)

np.float64(0.261308860174165)

In [131]:
pd.Series(data = np.abs(np.round(lr.coef_,1)), index=dropped_df.drop('count',axis=1).columns).sort_values(ascending=False)

season        23.3
atemp          5.5
weather        5.4
holiday        4.7
humidity       3.0
temp           1.9
windspeed      0.9
workingday     0.8
dtype: float64

In [114]:
X = dropped_df.drop(['count', 'workingday', 'windspeed', 'temp'],axis=1).values
y = dropped_df['count']

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [94]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [95]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(155.0761352604271), np.float64(24048.607727310282))

In [67]:
r2_score(y_test, y_pred)

np.float64(0.26185511637110925)

In [68]:
from sklearn.model_selection import cross_val_score
neg_mse_scores = cross_val_score(lr, X, y, scoring='neg_mean_squared_error', cv=5)
neg_mse_scores

array([-13698.21233362, -24507.81660116, -16066.89762602, -40581.7006381 ,
       -45481.08991632])

In [69]:
RMSE = np.sqrt(neg_mse_scores * (-1))
np.mean(RMSE), RMSE

(np.float64(163.0112633521338),
 array([117.03936233, 156.54972565, 126.75526666, 201.44900257,
        213.26295955]))

In [70]:
r2_scores = cross_val_score(lr, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([-0.38223363, -0.08848212,  0.03326709,  0.12877392,  0.03933621]),
 np.float64(-0.05386770591695358))

In [96]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=42, max_depth=8)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [97]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(147.79352714154993), np.float64(21842.926664940052))

In [73]:
r2_score(y_test, y_pred)

np.float64(0.3295560082300917)

In [74]:
neg_mse_scores = cross_val_score(rf, X, y, scoring='neg_mean_squared_error', cv=5)
neg_mse_scores

array([-13541.2665182 , -25928.63673041, -18667.1841574 , -43195.5744361 ,
       -43499.85283743])

In [75]:
RMSE = np.sqrt(neg_mse_scores * (-1))
np.mean(RMSE), RMSE

(np.float64(166.08404005369826),
 array([116.36694771, 161.02371481, 136.62790402, 207.83545038,
        208.56618335]))

In [76]:
r2_scores = cross_val_score(rf, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([-0.36639683, -0.15158596, -0.12319016,  0.07265811,  0.08118443]),
 np.float64(-0.09746608189335666))

현재까지 랜덤포레스트 단독 모델이 가장 낫다

| 모델         | 평가 지표 | 단독 예측 (Individual Prediction) | 교차 검증 (Cross-Validation) |
| :----------- | :-------- | :-------------------------------- | :--------------------------- |
| **리니어 모델** | RMSE      | 155.08                            | 163.01                       |
|              | R2        | 0.2619                            | -0.0539                      |
| **랜덤 포레스트** | RMSE      | 147.79                            | 166.08                       |
|              | R2        | 0.3296                            | -0.0975                      |

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [116]:
results = []
for degree in range(1,7):
    model_poly = Pipeline([
        ('poly',PolynomialFeatures(degree=degree, include_bias=False)),
        ('linear',LinearRegression())
    ])
    model_poly.fit(X_train, y_train)
    pred_poly = model_poly.predict(X_test)
    mse = mean_squared_error(y_test,pred_poly)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred_poly)
    results.append({
        'degree' : degree,
        'MSE' : mse,
        'RMSE' : rmse,
        'R2' : r2
    })
pd.DataFrame(results)

   degree            MSE        RMSE        R2
0       1   24048.607727  155.076135  0.261855
1       2   23347.372935  152.798472  0.283379
2       3   22876.278692  151.249062  0.297838
3       4   22358.819862  149.528659  0.313721
4       5   22387.713012  149.625242  0.312834
5       6  138562.448434  372.239773 -3.253018

다항회귀모델(선형)에서는 4차가 가장 높다

In [47]:
results = []
for degree in range(1,6):
    model_poly = Pipeline([
        ('poly',PolynomialFeatures(degree=degree, include_bias=False)),
        ('RF',RandomForestRegressor(random_state=22, max_depth=8))
    ])
    model_poly.fit(X_train, y_train)
    pred_poly = model_poly.predict(X_test)
    mse = mean_squared_error(y_test,pred_poly)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred_poly)
    results.append({
        'degree' : degree,
        'MSE' : mse,
        'RMSE' : rmse,
        'R2' : r2
    })
pd.DataFrame(results)

   degree           MSE        RMSE        R2
0       1  21891.336106  147.957210  0.328070
1       2  21893.763759  147.965414  0.327996
2       3  21961.988551  148.195778  0.325902
3       4  21991.710673  148.296024  0.324989
4       5  21936.983246  148.111388  0.326669

다항회귀모델(랜덤포레스트)에서는 단항이 가장 높다

결론적으로 랜덤포레스트 단독 모델일때 성능이 가장 높았다.

In [134]:
from sklearn.ensemble import GradientBoostingRegressor

In [135]:
gb_clf = GradientBoostingRegressor()
gb_clf.fit(X_train,y_train)
gb_pred = gb_clf.predict(X_test)

In [136]:
mse = mean_squared_error(y_test,gb_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(148.65826046661388), np.float64(22099.27840495962))

In [137]:
r2_score(y_test, gb_pred)

np.float64(0.32168758077472925)

In [138]:
from xgboost import XGBRegressor

In [139]:
xgb = XGBRegressor(n_estimators=400, learning_rate=0.1, max_depth=3, use_label_encoder=False)
evals = [(X_test_scaled, y_test)]
xgb.fit(X_train_scaled, y_train, early_stopping_rounds=40, 
        eval_set=evals, verbose=True)
xgb_pred = xgb.predict(X_test_scaled)

[0]	validation_0-rmse:242.81698
[1]	validation_0-rmse:228.58793
[2]	validation_0-rmse:216.44106
[3]	validation_0-rmse:205.91504
[4]	validation_0-rmse:197.00860
[5]	validation_0-rmse:189.31892
[6]	validation_0-rmse:182.73839
[7]	validation_0-rmse:177.20154
[8]	validation_0-rmse:172.73875
[9]	validation_0-rmse:168.92128
[10]	validation_0-rmse:165.81172
[11]	validation_0-rmse:163.09597
[12]	validation_0-rmse:160.92956
[13]	validation_0-rmse:159.03686
[14]	validation_0-rmse:157.58634
[15]	validation_0-rmse:156.24149
[16]	validation_0-rmse:155.12871
[17]	validation_0-rmse:154.28972
[18]	validation_0-rmse:153.50600
[19]	validation_0-rmse:152.87736
[20]	validation_0-rmse:152.38217
[21]	validation_0-rmse:151.95435
[22]	validation_0-rmse:151.62822
[23]	validation_0-rmse:151.23281
[24]	validation_0-rmse:150.91682
[25]	validation_0-rmse:150.73322
[26]	validation_0-rmse:150.60042
[27]	validation_0-rmse:150.48316
[28]	validation_0-rmse:150.29558
[29]	validation_0-rmse:150.20399
[30]	validation_0-rmse:150.05349
[31]	validation_0-rmse:149.88981
[32]	validation_0-rmse:149.83397
[33]	validation_0-rmse:149.79941
[34]	validation_0-rmse:149.76873
[35]	validation_0-rmse:149.64952
[36]	validation_0-rmse:149.55222
[37]	validation_0-rmse:149.48238
[38]	validation_0-rmse:149.44525
[39]	validation_0-rmse:149.41045
[40]	validation_0-rmse:149.35743
[41]	validation_0-rmse:149.33996
[42]	validation_0-rmse:149.30106
[43]	validation_0-rmse:149.25579
[44]	validation_0-rmse:149.24643
[45]	validation_0-rmse:149.21716
[46]	validation_0-rmse:149.20146
[47]	validation_0-rmse:149.21056
[48]	validation_0-rmse:149.19421
[49]	validation_0-rmse:149.17565
[50]	validation_0-rmse:149.17489
[51]	validation_0-rmse:149.14492
[52]	validation_0-rmse:149.13678
[53]	validation_0-rmse:149.11433
[54]	validation_0-rmse:149.03761
[55]	validation_0-rmse:148.94233
[56]	validation_0-rmse:148.92961
[57]	validation_0-rmse:148.92144
[58]	validation_0-rmse:148.92787
[59]	validation_0-rmse:148.91601
[60]	validation_0-rmse:148.89553
[61]	validation_0-rmse:148.86514
[62]	validation_0-rmse:148.85567
[63]	validation_0-rmse:148.77041
[64]	validation_0-rmse:148.76005
[65]	validation_0-rmse:148.74588
[66]	validation_0-rmse:148.68818
[67]	validation_0-rmse:148.69310
[68]	validation_0-rmse:148.69013
[69]	validation_0-rmse:148.68369
[70]	validation_0-rmse:148.68730
[71]	validation_0-rmse:148.68856
[72]	validation_0-rmse:148.61823
[73]	validation_0-rmse:148.62088
[74]	validation_0-rmse:148.58666
[75]	validation_0-rmse:148.57734
[76]	validation_0-rmse:148.55155
[77]	validation_0-rmse:148.54485
[78]	validation_0-rmse:148.54000
[79]	validation_0-rmse:148.53282
[80]	validation_0-rmse:148.49833
[81]	validation_0-rmse:148.49485
[82]	validation_0-rmse:148.52327
[83]	validation_0-rmse:148.52101
[84]	validation_0-rmse:148.48305
[85]	validation_0-rmse:148.45636
[86]	validation_0-rmse:148.48140
[87]	validation_0-rmse:148.44835
[88]	validation_0-rmse:148.44181
[89]	validation_0-rmse:148.44128
[90]	validation_0-rmse:148.44047
[91]	validation_0-rmse:148.44304
[92]	validation_0-rmse:148.44728
[93]	validation_0-rmse:148.41243
[94]	validation_0-rmse:148.42466
[95]	validation_0-rmse:148.41380
[96]	validation_0-rmse:148.40390
[97]	validation_0-rmse:148.40437
[98]	validation_0-rmse:148.37181
[99]	validation_0-rmse:148.37773
[100]	validation_0-rmse:148.36535
[101]	validation_0-rmse:148.36137
[102]	validation_0-rmse:148.36952
[103]	validation_0-rmse:148.36307
[104]	validation_0-rmse:148.32991
[105]	validation_0-rmse:148.33232
[106]	validation_0-rmse:148.34765
[107]	validation_0-rmse:148.36284
[108]	validation_0-rmse:148.35869
[109]	validation_0-rmse:148.32905
[110]	validation_0-rmse:148.32105
[111]	validation_0-rmse:148.33723
[112]	validation_0-rmse:148.37626
[113]	validation_0-rmse:148.37231
[114]	validation_0-rmse:148.36242
[115]	validation_0-rmse:148.34835
[116]	validation_0-rmse:148.33412
[117]	validation_0-rmse:148.32700
[118]	validation_0-rmse:148.34155
[119]	validation_0-rmse:148.33787
[120]	validation_0-rmse:148.31347
[121]	validation_0-rmse:148.30615
[122]	validation_0-rmse:148.31164
[123]	validation_0-rmse:148.31814
[124]	validation_0-rmse:148.31174
[125]	validation_0-rmse:148.28131
[126]	validation_0-rmse:148.25707
[127]	validation_0-rmse:148.26387
[128]	validation_0-rmse:148.24242
[129]	validation_0-rmse:148.24124
[130]	validation_0-rmse:148.24496
[131]	validation_0-rmse:148.24601
[132]	validation_0-rmse:148.24353
[133]	validation_0-rmse:148.23729
[134]	validation_0-rmse:148.23576
[135]	validation_0-rmse:148.23369
[136]	validation_0-rmse:148.23995
[137]	validation_0-rmse:148.24301
[138]	validation_0-rmse:148.22571
[139]	validation_0-rmse:148.24307
[140]	validation_0-rmse:148.23379
[141]	validation_0-rmse:148.26570
[142]	validation_0-rmse:148.27132
[143]	validation_0-rmse:148.25219
[144]	validation_0-rmse:148.25206
[145]	validation_0-rmse:148.25586
[146]	validation_0-rmse:148.26082
[147]	validation_0-rmse:148.28163
[148]	validation_0-rmse:148.30313
[149]	validation_0-rmse:148.29984
[150]	validation_0-rmse:148.30389
[151]	validation_0-rmse:148.30048
[152]	validation_0-rmse:148.30179
[153]	validation_0-rmse:148.31010
[154]	validation_0-rmse:148.31179
[155]	validation_0-rmse:148.31802
[156]	validation_0-rmse:148.31980
[157]	validation_0-rmse:148.36370
[158]	validation_0-rmse:148.36671
[159]	validation_0-rmse:148.35972
[160]	validation_0-rmse:148.36383

c:\Users\Admin\miniconda3\envs\hi_ml_env\lib\site-packages\xgboost\sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[161]	validation_0-rmse:148.32662
[162]	validation_0-rmse:148.33808
[163]	validation_0-rmse:148.33535
[164]	validation_0-rmse:148.35193
[165]	validation_0-rmse:148.34697
[166]	validation_0-rmse:148.34128
[167]	validation_0-rmse:148.34844
[168]	validation_0-rmse:148.34425
[169]	validation_0-rmse:148.35659
[170]	validation_0-rmse:148.36644
[171]	validation_0-rmse:148.36879
[172]	validation_0-rmse:148.37582
[173]	validation_0-rmse:148.37943
[174]	validation_0-rmse:148.38102
[175]	validation_0-rmse:148.37711
[176]	validation_0-rmse:148.37004
[177]	validation_0-rmse:148.36615

In [140]:
mse = mean_squared_error(y_test,xgb_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(148.22570905944775), np.float64(21970.860826176053))

In [141]:
r2_score(y_test, xgb_pred)

np.float64(0.32562921348053675)