In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [32]:
import os
# 노트북 파일이 있는 폴더로 이동 (예시)
os.chdir(r'C:\githome\hipython_rep')

# 변경 후 확인
print("변경 후:", os.getcwd())

변경 후: C:\githome\hipython_rep

In [33]:
df = pd.read_csv('data1/Dubizzle_used_car_sales.csv')

In [34]:
df.head()

,title,price_in_aed,kilometers,body_condition,mechanical_condition,seller_type,body_type,no_of_cylinders,transmission_type,regional_specs,horsepower,fuel_type,steering_side,year,color,emirate,motors_trim,company,model,date_posted
0,MITSUBISHI PAJERO 3.5L / 2013,26000,167390,Perfect inside and out,Perfect inside and out,Dealer,SUV,6,Automatic Transmission,GCC Specs,Unknown,Gasoline,Left Hand Side,2013.0,Silver,Dubai,GLS,mitsubishi,pajero,13/05/2022
1,chevrolet silverado,110000,39000,Perfect inside and out,Perfect inside and out,Dealer,SUV,8,Automatic Transmission,North American Specs,400 - 500 HP,Gasoline,Left Hand Side,2018.0,White,Sharjah,1500 High Country,chevrolet,silverado,14/01/2022
2,MERCEDES-BENZ E300 - 2014 - GCC SPEC - FULL OP...,78000,200000,Perfect inside and out,Perfect inside and out,Dealer,Sedan,6,Automatic Transmission,GCC Specs,400 - 500 HP,Gasoline,Left Hand Side,2014.0,Blue,Sharjah,E 300,mercedes-benz,e-class,05/05/2022
3,WARRANTY UNTIL APR 2023 || Ferrari 488 Spider ...,899000,27000,Perfect inside and out,Perfect inside and out,Dealer,Hard Top Convertible,8,Automatic Transmission,GCC Specs,600 - 700 HP,Gasoline,Left Hand Side,2018.0,Red,Dubai,Standard,ferrari,488-spider,30/04/2022
4,USED RENAULT DOKKER 2020,33000,69000,Perfect inside and out,Perfect inside and out,Owner,Wagon,4,Manual Transmission,GCC Specs,Less than 150 HP,Gasoline,Left Hand Side,2020.0,White,Dubai,Standard,renault,dokker,13/05/2022

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9970 entries, 0 to 9969
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 9965 non-null   object
 1   price_in_aed          9970 non-null   int64
 2   kilometers            9970 non-null   int64
 3   body_condition        9970 non-null   object
 4   mechanical_condition  9970 non-null   object
 5   seller_type           9970 non-null   object
 6   body_type             9970 non-null   object
 7   no_of_cylinders       9889 non-null   object
 8   transmission_type     9970 non-null   object
 9   regional_specs        9970 non-null   object
 10  horsepower            9970 non-null   object
 11  fuel_type             9970 non-null   object
 12  steering_side         9970 non-null   object
 13  year                  9000 non-null   float64
 14  color                 9970 non-null   object
 15  emirate               9970 non-null   object
 16  motors_trim           9942 non-null   object
 17  company               9970 non-null   object
 18  model                 9970 non-null   object
 19  date_posted           9970 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.5+ MB

In [36]:
# 결측치 개수
missing_count = df.isnull().sum()

# 전체 대비 결측치 비율(%)
missing_ratio = (missing_count / len(df)) * 100

# 결측치 요약표 출력
missing_df = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Ratio (%)': missing_ratio
}).sort_values(by='Missing Count', ascending=False)

missing_df[missing_df['Missing Count'] > 0]

                 Missing Count  Missing Ratio (%)
year                       970           9.729188
no_of_cylinders             81           0.812437
motors_trim                 28           0.280843
title                        5           0.050150

In [41]:
no_null_df = df.copy()
no_null_df['no_of_cylinders'].fillna(no_null_df['no_of_cylinders'].mode()[0],inplace=True)
no_null_df['motors_trim'].fillna('unknown',inplace=True)
no_null_df['title'].fillna('unknown',inplace=True)
no_null_df['year'].fillna(no_null_df['year'].median(),inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19024\3555952243.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  no_null_df['no_of_cylinders'].fillna(no_null_df['no_of_cylinders'].mode()[0],inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19024\3555952243.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  no_null_df['motors_trim'].fillna('unknown',inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19024\3555952243.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  no_null_df['title'].fillna('unknown',inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19024\3555952243.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  no_null_df['year'].fillna(no_null_df['year'].median(),inplace=True)

In [42]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
le = LabelEncoder()

In [43]:
encoded_df = no_null_df.copy()
for col in encoded_df.columns:
    if encoded_df[col].dtype == 'object':
        encoded_df[col] = le.fit_transform(encoded_df[col])

In [44]:
encoded_df.head()

,title,price_in_aed,kilometers,body_condition,mechanical_condition,seller_type,body_type,no_of_cylinders,transmission_type,regional_specs,horsepower,fuel_type,steering_side,year,color,emirate,motors_trim,company,model,date_posted
0,6507,26000,167390,3,4,0,6,5,0,1,10,2,0,2013.0,12,3,386,51,371,154
1,8929,110000,39000,3,4,0,6,6,0,3,3,2,0,2018.0,15,6,19,10,457,160
2,6451,78000,200000,3,4,0,7,5,0,1,3,2,0,2014.0,2,6,296,46,177,54
3,8823,899000,27000,3,4,0,2,6,0,1,5,2,0,2018.0,11,3,723,16,30,333
4,8614,33000,69000,3,4,2,12,3,1,1,9,2,0,2020.0,15,3,723,59,172,154

In [45]:
X = encoded_df.drop('price_in_aed',axis=1).values
y = encoded_df['price_in_aed']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
lr = LinearRegression()
lr.fit(X_train_scaled,y_train)
y_pred = lr.predict(X_test_scaled)

In [48]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(409321.05529370083), np.float64(167543726306.74887))

In [49]:
r2_score(y_test, y_pred)

np.float64(0.15872922130211664)

In [50]:
pd.Series(data = np.abs(np.round(lr.coef_,1)), index=encoded_df.drop('price_in_aed',axis=1).columns).sort_values(ascending=False)

horsepower              82182.7
year                    78162.9
seller_type             64038.4
color                   40602.1
regional_specs          33912.7
company                 25696.3
motors_trim             19976.4
transmission_type       19371.3
fuel_type               17476.9
no_of_cylinders         17454.3
title                   16354.9
model                   15079.8
body_type               14385.2
emirate                 13598.3
body_condition           7689.4
kilometers               5585.8
mechanical_condition     4310.7
steering_side            2413.6
date_posted              1132.5
dtype: float64

In [61]:
X = encoded_df.drop(['price_in_aed', 'date_posted', 'steering_side'],axis=1).values
y = encoded_df['price_in_aed']

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
lr = LinearRegression()
lr.fit(X_train_scaled,y_train)
y_pred = lr.predict(X_test_scaled)

In [64]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(409330.9773900221), np.float64(167551849051.07077))

In [65]:
r2_score(y_test, y_pred)

np.float64(0.15868843536765354)

In [66]:
from sklearn.model_selection import cross_val_score
neg_mse_scores = cross_val_score(lr, X, y, scoring='neg_mean_squared_error', cv=5)
neg_mse_scores

array([-2.01521777e+13, -1.45012509e+11, -2.48066673e+11, -1.51168493e+11,
       -1.43765720e+11])

In [67]:
RMSE = np.sqrt(neg_mse_scores * (-1))
np.mean(RMSE), RMSE

(np.float64(1227190.8262765508),
 array([4489117.70182181,  380805.07959723,  498062.921147  ,
         388803.92671001,  379164.50210671]))

In [68]:
r2_scores = cross_val_score(lr, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([-8.36270042e+01,  1.56973068e-01,  7.97636296e-02,  1.49351633e-01,
         1.60964525e-01]),
 np.float64(-16.615990261965102))

In [69]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=42, max_depth=8)
rf.fit(X_train_scaled,y_train)
y_pred = rf.predict(X_test_scaled)

In [70]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

rmse, mse

(np.float64(214068.31901716476), np.float64(45825245206.834625))

In [71]:
r2_score(y_test, y_pred)

np.float64(0.7699022185492461)

In [72]:
neg_mse_scores = cross_val_score(rf, X, y, scoring='neg_mean_squared_error', cv=5)
neg_mse_scores

array([-5.37935057e+10, -3.83944620e+10, -1.08023877e+11, -4.44078856e+10,
       -2.00488039e+10])

In [73]:
RMSE = np.sqrt(neg_mse_scores * (-1))
np.mean(RMSE), RMSE

(np.float64(221774.95280178468),
 array([231934.27023239, 195945.04831144, 328669.86067238, 210731.78586989,
        141593.79892281]))

In [74]:
r2_scores = cross_val_score(rf, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([0.77409969, 0.77679467, 0.59927104, 0.75011   , 0.88299257]),
 np.float64(0.7566535910922498))

In [75]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [76]:
results = []
for degree in range(1,6):
    model_poly = Pipeline([
        ('poly',PolynomialFeatures(degree=degree, include_bias=False)),
        ('linear',LinearRegression())
    ])
    model_poly.fit(X_train_scaled, y_train)
    pred_poly = model_poly.predict(X_test_scaled)
    mse = mean_squared_error(y_test,pred_poly)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred_poly)
    results.append({
        'degree' : degree,
        'MSE' : mse,
        'RMSE' : rmse,
        'R2' : r2
    })
pd.DataFrame(results)

   degree           MSE          RMSE            R2
0       1  1.675518e+11  4.093310e+05  1.586884e-01
1       2  9.259381e+10  3.042923e+05  5.350678e-01
2       3  1.809893e+12  1.345323e+06 -8.087837e+00
3       4  1.211254e+15  3.480308e+07 -6.080951e+03
4       5  4.921698e+19  7.015482e+09 -2.471284e+08

In [77]:
results = []
best_r2 = False
for degree in range(1,6):
    model_poly = Pipeline([
        ('poly',PolynomialFeatures(degree=degree, include_bias=False)),
        ('RF',RandomForestRegressor(random_state=22, max_depth=8))
    ])
    model_poly.fit(X_train_scaled, y_train)
    pred_poly = model_poly.predict(X_test_scaled)
    mse = mean_squared_error(y_test,pred_poly)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, pred_poly)
    results.append({
        'degree' : degree,
        'MSE' : mse,
        'RMSE' : rmse,
        'R2' : r2
    })
    if best_r2 < r2 or best_r2 == False:
        best_r2 = r2
        best_model = model_poly
        best_pred_poly = pred_poly
pd.DataFrame(results)

   degree           MSE           RMSE        R2
0       1  3.994577e+10  199864.372722  0.799424
1       2  3.046984e+10  174556.119275  0.847005
2       3  3.713333e+10  192700.098863  0.813546
3       4  3.902279e+10  197541.874625  0.804059
4       5  3.483439e+10  186639.724834  0.825090